/* Automatically generated by kernel/timeconst.pl */
/* Conversion constants for HZ == 300 */

#ifndef KERNEL_TIMECONST_H
#define KERNEL_TIMECONST_H

#include <linux/param.h>
#include <linux/types.h>

#if HZ != 300
#error "kernel/timeconst.h has the wrong HZ value!"
#endif

#define HZ_TO_MSEC_MUL32        U64_C(0xd5555556)
#define HZ_TO_MSEC_ADJ32        U64_C(0x2aaaaaaa)
#define HZ_TO_MSEC_SHR32        30
#define HZ_TO_MSEC_NUM          U64_C(10)
#define HZ_TO_MSEC_DEN          U64_C(3)
#define MSEC_TO_HZ_MUL32        U64_C(0x9999999a)
#define MSEC_TO_HZ_ADJ32        U64_C(0x1cccccccc)
#define MSEC_TO_HZ_SHR32        33
#define MSEC_TO_HZ_NUM          U64_C(3)
#define MSEC_TO_HZ_DEN          U64_C(10)
#define HZ_TO_USEC_MUL32        U64_C(0xd0555556)
#define HZ_TO_USEC_ADJ32        U64_C(0xaaaaa)
#define HZ_TO_USEC_SHR32        20
#define HZ_TO_USEC_NUM          U64_C(10000)
#define HZ_TO_USEC_DEN          U64_C(3)
#define USEC_TO_HZ_MUL32        U64_C(0x9d495183)
#define USEC_TO_HZ_ADJ32        U64_C(0x7ffcb923a29)
#define USEC_TO_HZ_SHR32        43
#define USEC_TO_HZ_NUM          U64_C(3)
#define USEC_TO_HZ_DEN          U64_C(10000)

#endif /* KERNEL_TIMECONST_H */
